package com.hm.util.model;

// Generated Jun 13, 2016 4:36:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ActivityVo generated by hbm2java
 */
public class ActivityVo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String activityName;
	private String activityCode;
	private Long addedBy;
	private Date addedOn;
	private Long modifiedBy;
	private Date modifiedOn;
	private Integer status;
	private String completionPercentage;
	private String remarks;
	private Integer ticketType;


	public ActivityVo() {
	}

	public ActivityVo(Integer id, String activityName) {
		this.id = id;
		this.activityName = activityName;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	public Long getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(Long addedBy) {
		this.addedBy = addedBy;
	}

	public Date getAddedOn() {
		return this.addedOn;
	}

	public void setAddedOn(Date addedOn) {
		this.addedOn = addedOn;
	}

	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCompletionPercentage() {
		return this.completionPercentage;
	}

	public void setCompletionPercentage(String completionPercentage) {
		this.completionPercentage = completionPercentage;
	}

	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((activityName == null) ? 0 : activityName.hashCode());
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ActivityVo other = (ActivityVo) obj;
		if (activityName == null)
		{
			if (other.activityName != null)
				return false;
		} else if (!activityName.equals(other.activityName))
			return false;
		if (id != other.id)
			return false;
		return true;
	}

	public String getActivityCode()
	{
		return activityCode;
	}

	public void setActivityCode(String activityCode)
	{
		this.activityCode = activityCode;
	}

	public String getRemarks()
	{
		return remarks;
	}

	public void setRemarks(String remarks)
	{
		this.remarks = remarks;
	}
	
	

	public Integer getTicketType() {
		return ticketType;
	}

	public void setTicketType(Integer ticketType) {
		this.ticketType = ticketType;
	}

	@Override
	public String toString() {
		return "ActivityVo [id=" + id + ", activityName=" + activityName + ", activityCode=" + activityCode
				+ ", status=" + status + "]";
	}

}
